enableVersioning: false
handle: mainNavigation
name: 'Main Navigation'
previewTargets:
  -
    __assoc__:
      -
        - label
        - Production
      -
        - urlFormat
        - '@previewProduction'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Staging
      -
        - urlFormat
        - '@previewStaging'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2db749af-5480-4975-830e-eff6615b8e4c:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '__home__?nav={slug}'
structure:
  maxLevels: null
  uid: 7a6921b6-e440-40ec-bae7-7303f4bb05d8
type: structure
