enableVersioning: true
handle: posts
name: Posts
previewTargets:
  -
    __assoc__:
      -
        - label
        - Production
      -
        - urlFormat
        - '@previewProduction'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - Staging
      -
        - urlFormat
        - '@previewStaging'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2db749af-5480-4975-830e-eff6615b8e4c:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'posts/{slug}'
type: channel
